config:
  target: 'http://localhost:8080'
  phases:
    - duration: 10
      arrivalRate: 1000
      name: Sustained 1000 users for 10 seconds
scenarios:
  - flow:
      - get:
          url: '/carts/3'
